CREATE TABLE IF NOT EXISTS `users` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    `email` VARCHAR(32) NOT NULL UNIQUE,
    `password` VARCHAR(64) NOT NULL,
    `username` VARCHAR(32) NOT NULL UNIQUE,
    `bio` VARCHAR(256) NULL,
    `image` VARCHAR(256) NULL
)
